package Shapez.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptCanvas = createDescriptorForCanvas();
  /*package*/ final ConceptDescriptor myConceptCircle = createDescriptorForCircle();
  /*package*/ final ConceptDescriptor myConceptColor = createDescriptorForColor();
  /*package*/ final ConceptDescriptor myConceptColorReference = createDescriptorForColorReference();
  /*package*/ final ConceptDescriptor myConceptShape = createDescriptorForShape();
  /*package*/ final ConceptDescriptor myConceptShapeColor = createDescriptorForShapeColor();
  /*package*/ final ConceptDescriptor myConceptSquare = createDescriptorForSquare();
  /*package*/ final ConceptDescriptor myConceptTriangle = createDescriptorForTriangle();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.extendedLanguage(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, "jetbrains.mps.execution.util");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCanvas, myConceptCircle, myConceptColor, myConceptColorReference, myConceptShape, myConceptShapeColor, myConceptSquare, myConceptTriangle);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Canvas:
        return myConceptCanvas;
      case LanguageConceptSwitch.Circle:
        return myConceptCircle;
      case LanguageConceptSwitch.Color:
        return myConceptColor;
      case LanguageConceptSwitch.ColorReference:
        return myConceptColorReference;
      case LanguageConceptSwitch.Shape:
        return myConceptShape;
      case LanguageConceptSwitch.ShapeColor:
        return myConceptShapeColor;
      case LanguageConceptSwitch.Square:
        return myConceptSquare;
      case LanguageConceptSwitch.Triangle:
        return myConceptTriangle;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForCanvas() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapez", "Canvas", 0xbf730aef8e694202L, 0x919a4a1203c3a8aaL, 0x724cd02669807df8L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L);
    b.origin("r:19f796dc-4132-4cb0-888a-3287d5bc8a1f(Shapez.structure)/8236186681951157752");
    b.version(3);
    b.aggregate("shapes", 0x724cd026698086f3L).target(0xbf730aef8e694202L, 0x919a4a1203c3a8aaL, 0x724cd02669807de3L).optional(true).ordered(true).multiple(true).origin("8236186681951160051").done();
    b.alias("canvas");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCircle() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapez", "Circle", 0xbf730aef8e694202L, 0x919a4a1203c3a8aaL, 0x724cd02669807de7L);
    b.class_(false, false, false);
    // extends: Shapez.structure.Shape
    b.super_(0xbf730aef8e694202L, 0x919a4a1203c3a8aaL, 0x724cd02669807de3L);
    b.origin("r:19f796dc-4132-4cb0-888a-3287d5bc8a1f(Shapez.structure)/8236186681951157735");
    b.version(3);
    b.property("radius", 0x724cd02669807deaL).type(PrimitiveTypeId.INTEGER).origin("8236186681951157738").done();
    b.property("x", 0x724cd02669807deeL).type(PrimitiveTypeId.INTEGER).origin("8236186681951157742").done();
    b.property("y", 0x724cd02669807defL).type(PrimitiveTypeId.INTEGER).origin("8236186681951157743").done();
    b.alias("circle");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForColor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapez", "Color", 0xbf730aef8e694202L, 0x919a4a1203c3a8aaL, 0x724cd02669818634L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:19f796dc-4132-4cb0-888a-3287d5bc8a1f(Shapez.structure)/8236186681951225396");
    b.version(3);
    b.alias("color");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForColorReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapez", "ColorReference", 0xbf730aef8e694202L, 0x919a4a1203c3a8aaL, 0x724cd0266982f7efL);
    b.class_(false, false, false);
    b.origin("r:19f796dc-4132-4cb0-888a-3287d5bc8a1f(Shapez.structure)/8236186681951320047");
    b.version(3);
    b.associate("target", 0x724cd0266982f7f3L).target(0xbf730aef8e694202L, 0x919a4a1203c3a8aaL, 0x724cd02669818634L).optional(false).origin("8236186681951320051").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForShape() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapez", "Shape", 0xbf730aef8e694202L, 0x919a4a1203c3a8aaL, 0x724cd02669807de3L);
    b.class_(false, true, false);
    b.origin("r:19f796dc-4132-4cb0-888a-3287d5bc8a1f(Shapez.structure)/8236186681951157731");
    b.version(3);
    b.aggregate("color", 0x724cd0266982f809L).target(0xbf730aef8e694202L, 0x919a4a1203c3a8aaL, 0x724cd0266982f7efL).optional(false).ordered(true).multiple(false).origin("8236186681951320073").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForShapeColor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapez", "ShapeColor", 0xbf730aef8e694202L, 0x919a4a1203c3a8aaL, 0x724cd0266982f80cL);
    b.class_(false, false, false);
    b.origin("r:19f796dc-4132-4cb0-888a-3287d5bc8a1f(Shapez.structure)/8236186681951320076");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSquare() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapez", "Square", 0xbf730aef8e694202L, 0x919a4a1203c3a8aaL, 0x724cd02669807df2L);
    b.class_(false, false, false);
    // extends: Shapez.structure.Shape
    b.super_(0xbf730aef8e694202L, 0x919a4a1203c3a8aaL, 0x724cd02669807de3L);
    b.origin("r:19f796dc-4132-4cb0-888a-3287d5bc8a1f(Shapez.structure)/8236186681951157746");
    b.version(3);
    b.property("upperLeftX", 0x724cd02669807df3L).type(PrimitiveTypeId.INTEGER).origin("8236186681951157747").done();
    b.property("upperLeftY", 0x724cd02669807df4L).type(PrimitiveTypeId.INTEGER).origin("8236186681951157748").done();
    b.property("size", 0x724cd02669807df5L).type(PrimitiveTypeId.INTEGER).origin("8236186681951157749").done();
    b.alias("square");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTriangle() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapez", "Triangle", 0xbf730aef8e694202L, 0x919a4a1203c3a8aaL, 0x570ffcfc6e2f853aL);
    b.class_(false, false, false);
    // extends: Shapez.structure.Shape
    b.super_(0xbf730aef8e694202L, 0x919a4a1203c3a8aaL, 0x724cd02669807de3L);
    b.origin("r:19f796dc-4132-4cb0-888a-3287d5bc8a1f(Shapez.structure)/6273510967060956474");
    b.version(3);
    b.property("x1", 0x570ffcfc6e2f859fL).type(PrimitiveTypeId.INTEGER).origin("6273510967060956575").done();
    b.property("y1", 0x570ffcfc6e2f85b4L).type(PrimitiveTypeId.INTEGER).origin("6273510967060956596").done();
    b.property("x2", 0x570ffcfc6e2f85d3L).type(PrimitiveTypeId.INTEGER).origin("6273510967060956627").done();
    b.property("y2", 0x570ffcfc6e2f85f2L).type(PrimitiveTypeId.INTEGER).origin("6273510967060956658").done();
    b.property("x3", 0x570ffcfc6e2f8607L).type(PrimitiveTypeId.INTEGER).origin("6273510967060956679").done();
    b.property("y3", 0x570ffcfc6e2f8612L).type(PrimitiveTypeId.INTEGER).origin("6273510967060956690").done();
    b.alias("triangle");
    return b.create();
  }
}
